CONFIG_ZMK_BACKLIGHT=y

# https://github.com/TinNotTim/nau7802_loadcell_zephyr_driver
CONFIG_SENSOR=y
CONFIG_NAU7802_LOADCELL=y
# Interrut triggerred configurations
CONFIG_NAU7802_LOADCELL_TRIGGER_NONE=y
CONFIG_NAU7802_LOADCELL_TRIGGER_OWN_THREAD=y
CONFIG_NAU7802_LOADCELL_TRIGGER_GLOBAL_THREAD=y
CONFIG_NAU7802_LOADCELL_TRIGGER_DIRECT=y